WebApp/WebApp/Controllers/ContactGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApp.Helpers;
using WebApp.Helpers.Toast;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class ContactGroupsController : Controller
    {
        // GET: ContactGroups
        public async Task<ActionResult> Index()
        {
            var groups = await APIClient.GetAllGroups(Session["AccessToken"].ToString());
            return View(groups);
        }

        // GET: ContactGroups/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                var group = APIClient.GetGroup(Session["AccessToken"].ToString(), id);

                return View(group);

            }
            catch (HttpException e)
            {
                ViewBag.ErrorMessage = e.Message;
                this.AddToastMessage("Fejl!", e.Message, ToastType.Error);

                return View();
            }
        }

        // GET: ContactGroups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ContactGroups/Create
        [HttpPost]
        public ActionResult Create(ContactGroupViewModel model)
        {
            try
            {
                var res = APIClient.CreateGroup(Session["AccessToken"].ToString(), model);

                if (res.StatusCode == HttpStatusCode.OK)
                {
                    this.AddToastMessage("Succes", "Medarbejderen blev oprettet.", ToastType.Success);
                }

                return RedirectToAction("Index");
            }
            catch (HttpException e)
            {
                ViewBag.ErrorMessage = e.Message;
                this.AddToastMessage("Fejl", e.Message, ToastType.Error);

                return View(model);
            }
        }

        // GET: ContactGroups/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var group = APIClient.GetGroup(Session["AccessToken"].ToString(), id);
                return View(group);
            }
            catch (HttpException e)
            {
                ViewBag.ErrorMessage = e.Message;
                this.AddToastMessage("Fejl", e.Message, ToastType.Error);

                return View();
            }
        }

        // POST: ContactGroups/Edit/5
        [HttpPut]
        public ActionResult Edit(int id, ContactGroupViewModel model)
        {
            try
            {
                var res = APIClient.EditGroup(Session["AccessToken"].ToString(), id, model);

                if (res.StatusCode == HttpStatusCode.OK)
                {
                    this.AddToastMessage("Succes", "Medarbejderens oplysninger er blevet ændret.", ToastType.Success);
                }

                return RedirectToAction("Index");
            }
            catch (HttpException e)
            {
                ViewBag.ErrorMessage = e.Message;
                this.AddToastMessage("Fejl", e.Message, ToastType.Error);

                return View(model);
            }
        }

        // GET: ContactGroups/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                var group = APIClient.GetGroup(Session["AccessToken"].ToString(), id);

                return View(group);
            }
            catch (HttpException e)
            {
                ViewBag.ErrorMessage = e.Message;
                this.AddToastMessage("Fejl", e.Message, ToastType.Error);

                return View();
            }
        }

        // POST: ContactGroups/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, ContactGroupViewModel model)
        {
            try
            {
                var res = APIClient.DeleteGroup(Session["AccessToken"].ToString(), id);

                if (res.StatusCode == HttpStatusCode.OK)
                {
                    this.AddToastMessage("Succes!", "Kontaktgruppen er blevet slettet.", ToastType.Success);
                }

                return RedirectToAction("Index");
            }
            catch (HttpException e)
            {
                ViewBag.ErrorMessage = e.Message;
                this.AddToastMessage("Fejl", e.Message, ToastType.Error);

                return View(model);
            }
        }
    }
}

WebApp/WebApp/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApp.Helpers;
using WebApp.Helpers.Toast;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class ContactsController : Controller
    {
        // GET: Contacts
        public async Task<ActionResult> Index(string errorMessage = "")
        {
            var contacts = await APIClient.GetAllContacts(Session["AccessToken"].ToString());
            var contactGroups = await APIClient.GetAllGroups(Session["AccessToken"].ToString());

            var groupList = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Ingen", Value = "Ingen"}
            };

            foreach (var group in contactGroups)
            {
                groupList.Add(new SelectListItem
                {
                    Text = group.Name,
                    Value = group.Id.ToString()
                });
            }
            ViewBag.groupList = groupList;

            return View(contacts);
        }

        [HttpPost]
        public ActionResult Index(string id, string name, string email, string phone, string groupList = "")
        {
            try
            {
                int idAsInt = 0;
                Int32.TryParse(id, out idAsInt);

                ContactViewModel model = new ContactViewModel
                {
                    Id = idAsInt,
                    Name = name,
                    Email = email,
                    Phone = phone
                };

                try
                {
                    var res = APIClient.EditContact(Session["AccessToken"].ToString(), idAsInt, model, groupList);

                    if (res.StatusCode == HttpStatusCode.OK)
                    {
                        this.AddToastMessage("Succes", "Kontaktpersonen er opdateret.", ToastType.Success);

                    }
                }
                catch (HttpException e)
                {
                    this.AddToastMessage("Fejl!", e.Message, ToastType.Error);
                    return RedirectToAction("Index");
                }

                return RedirectToAction("Index");

            }
            catch (HttpException e)
            {
                return RedirectToAction("Index", new { errorMessage = e.Message });
            }
        }

        // GET: Contacts/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                var contact = APIClient.GetContact(Session["AccessToken"].ToString(), id);

                return View(contact);

            }
            catch (HttpException e)
            {
                ViewBag.ErrorMessage = e.Message;
                this.AddToastMessage("Fejl!", e.Message, ToastType.Error);

                return View();
            }
        }

        // GET: Contacts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contacts/Create
        [HttpPost]
        public ActionResult Create(ContactViewModel model)
        {
            try
            {
                var res = APIClient.CreateContact(Session["AccessToken"].ToString(), model);

                if (res.StatusCode == HttpStatusCode.OK)
                {
                    this.AddToastMessage("Succes", "Medarbejderen blev oprettet.", ToastType.Success);
                }

                return RedirectToAction("Index");
            }
            catch (HttpException e)
            {
                ViewBag.ErrorMessage = e.Message;
                this.AddToastMessage("Fejl", e.Message, ToastType.Error);

                return View(model);
            }
        }

        // GET: Contacts/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var contact = APIClient.GetContact(Session["AccessToken"].ToString(), id);
                return View(contact);
            }
            catch (HttpException e)
            {
                ViewBag.ErrorMessage = e.Message;
                this.AddToastMessage("Fejl", e.Message, ToastType.Error);

                return View();
            }
        }

        // POST: Contacts/Edit/5
        [HttpPut]
        public ActionResult Edit(int id, ContactViewModel model)
        {
            try
            {
                var res = APIClient.EditContact(Session["AccessToken"].ToString(), id, model, "");

                if (res.StatusCode == HttpStatusCode.OK)
                {
                    this.AddToastMessage("Succes", "Medarbejderens oplysninger er blevet ændret.", ToastType.Success);
                }

                return RedirectToAction("Index");
            }
            catch (HttpException e)
            {
                ViewBag.ErrorMessage = e.Message;
                this.AddToastMessage("Fejl", e.Message, ToastType.Error);

                return View(model);
            }
        }

        // GET: Contacts/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                var contact = APIClient.GetContact(Session["AccessToken"].ToString(), id);

                return View(contact);
            }
            catch (HttpException e)
            {
                ViewBag.ErrorMessage = e.Message;
                this.AddToastMessage("Fejl", e.Message, ToastType.Error);

                return View();
            }
        }

        // POST: Contacts/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, ContactViewModel model)
        {
            try
            {
                var res = APIClient.DeleteContact(Session["AccessToken"].ToString(), id);

                if (res.StatusCode == HttpStatusCode.OK)
                {
                    this.AddToastMessage("Succes!", "Kontaktoplysningerne er blevet slettet.", ToastType.Success);
                }

                return RedirectToAction("Index");
            }
            catch (HttpException e)
            {
                ViewBag.ErrorMessage = e.Message;
                this.AddToastMessage("Fejl", e.Message, ToastType.Error);

                return View();
            }
        }
    }
}

WebApp/WebApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Helpers;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var tokenForSession = LoginClient.Login(model.Email, model.Password);

            if (tokenForSession?.Token == null)
            {
                var err = "Ugyldig kombination af email og password.";
                ModelState.AddModelError("", err);
                return View(model);
            }

            Session["AccessToken"] = tokenForSession.Token;
            Session["TokenExpires"] = tokenForSession.Expires;
            Session["LoggedIn"] = true;

            return RedirectToAction("Index", "Accounts");
        }

        [HttpGet]
        public ActionResult LogOut()
        {
            Session["AccessToken"] = null;
            Session["TokenExpires"] = null;
            Session["LoggedIn"] = false;
            Session["Username"] = null;
            Session["Role"] = null;

            return RedirectToAction("Index", "Home");
        }
    }
}

WebApp/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Salus Nord</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Salus Nord", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (
                        Session["LoggedIn"] != null &&
                        (bool)Session["LoggedIn"] &&
                        (string)Session["role"] == "Provider")
                    {
                        <li>@Html.ActionLink("Administratorer", "Index", "Provider")</li>
                        <li>@Html.ActionLink("Plejehjem", "Index", "NursingHome")</li>
                    }

                    @if (
                        Session["LoggedIn"] != null &&
                        (bool)Session["LoggedIn"] &&
                        (string)Session["role"] == "NursingHome")
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" id="productDropdown" data-toggle="dropdown" href="#">Kontakter<span class="caret" style="margin-left: 5px"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Kontakter", "Index", "Contacts")</li>
                                <li>@Html.ActionLink("Kontaktgrupper", "Index", "ContactGroups")</li>

                            </ul>
                        </li>
                        <li>@Html.ActionLink("Beboere", "Index", "Residents")</li>
                    }
                </ul>

                @if (Session["LoggedIn"] != null && (bool)Session["LoggedIn"])
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li> @Html.ActionLink("Velkommen " + ((string)Session["Username"]), "Index", "Accounts")</li>
                        <li>@Html.ActionLink("Log ud", "Logout", "Login", new { returnUrl = "/Home/Index" }, null)</li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Log ind", "Index", "Login")</li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Salus Nord IVS</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>